"""Add is_in_stock to plants

Revision ID: 52862a3166ec
Revises: 3d442f052cae
Create Date: 2025-06-26 00:17:57.156112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52862a3166ec'
down_revision = '3d442f052cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_in_stock', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('is_in_stock')

    # ### end Alembic commands ###
